"""empty message

Revision ID: 1a7da5a9371a
Revises: f6ff890f8963
Create Date: 2021-04-14 11:31:55.775997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7da5a9371a'
down_revision = 'f6ff890f8963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('date', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'date')
    # ### end Alembic commands ###
