"""empty message

Revision ID: acf105bd2d66
Revises: a76bb5f7bf4f
Create Date: 2021-04-13 11:57:14.538114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf105bd2d66'
down_revision = 'a76bb5f7bf4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_id', sa.Integer(), nullable=False))
    op.drop_column('tasks', 'id')
    op.add_column('users', sa.Column('authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authenticated')
    op.add_column('tasks', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('tasks', 'task_id')
    # ### end Alembic commands ###
