"""empty message

Revision ID: c6656c517956
Revises: 1a7da5a9371a
Create Date: 2021-04-21 13:12:56.924433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6656c517956'
down_revision = '1a7da5a9371a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('end_date', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('start_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'start_date')
    op.drop_column('tasks', 'end_date')
    # ### end Alembic commands ###
